[package]
name = "_impl"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = "1"
syn = { version = "1", features = ["full", "extra-traits"] }

[[test]]
name = "test-pos"
path = "test-pos.rs"
